name = "workers-rs-2"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

assets = { directory = "./public/" }

[build]
command = "cargo install -q worker-build && worker-build --release"

