CREATE TABLE todos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT,
  completed BOOLEAN DEFAULT 0,
  content_type TEXT,
  is_public BOOLEAN DEFAULT 0,
  food_orange BOOLEAN DEFAULT 0,
  food_apple BOOLEAN DEFAULT 0,
  food_banana BOOLEAN DEFAULT 0,
  food_melon BOOLEAN DEFAULT 0,
  food_grape BOOLEAN DEFAULT 0,
  pub_date1 TEXT,
  pub_date2 TEXT,
  pub_date3 TEXT,
  pub_date4 TEXT,
  pub_date5 TEXT,
  pub_date6 TEXT,
  qty1 TEXT,
  qty2 TEXT,
  qty3 TEXT,
  qty4 TEXT,
  qty5 TEXT,
  qty6 TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);